import type { ResolvedLocale } from '@/libs/i18n'

export interface PrintableText {
  htmlLang: string
  title: string
  statTotal: string
  statOpen: string
  statFixed: string
  statIgnored: string
  statDanger: string
  summaryTotal: string
  summaryBySeverity: string
  summaryByStatus: string
  summaryByHumanStatus: string
  summaryByType: string
  noFilters: string
  logoSubtitle: string
  topCaption: string
  version: string
  exportedAt: string
  summaryAria: string
  filtersSection: string
  summarySection: string
  detailsSection: string
  noDetails: string
  generatedBy: string
  severityTag: string
  statusTag: string
  humanStatusTag: string
  description: string
  risk: string
  fixSuggestion: string
  na: string
}

export const PRINTABLE_TEXT: Record<ResolvedLocale, PrintableText> = {
  'zh-TW': {
    htmlLang: 'zh-Hant',
    title: 'Confession 漏洞匯出報告',
    statTotal: '總漏洞',
    statOpen: '待處理',
    statFixed: '已修復',
    statIgnored: '已忽略',
    statDanger: '嚴重+高風險',
    summaryTotal: '總漏洞數',
    summaryBySeverity: '依嚴重度',
    summaryByStatus: '依狀態',
    summaryByHumanStatus: '依審核狀態',
    summaryByType: '依漏洞類型',
    noFilters: '（無篩選）',
    logoSubtitle: 'Security Vulnerability Report',
    topCaption: 'Cyber Security Analysis Snapshot',
    version: '版本',
    exportedAt: '匯出時間',
    summaryAria: '重點摘要',
    filtersSection: '篩選條件',
    summarySection: '統計摘要',
    detailsSection: '漏洞明細',
    noDetails: '（沒有符合條件的漏洞）',
    generatedBy: 'Generated by Confession',
    severityTag: 'severity',
    statusTag: 'status',
    humanStatusTag: 'humanStatus',
    description: '描述',
    risk: '風險',
    fixSuggestion: '修復建議',
    na: 'N/A',
  },
  'zh-CN': {
    htmlLang: 'zh-Hans',
    title: 'Confession 漏洞导出报告',
    statTotal: '总漏洞',
    statOpen: '待处理',
    statFixed: '已修复',
    statIgnored: '已忽略',
    statDanger: '严重+高风险',
    summaryTotal: '总漏洞数',
    summaryBySeverity: '按严重度',
    summaryByStatus: '按状态',
    summaryByHumanStatus: '按审核状态',
    summaryByType: '按漏洞类型',
    noFilters: '（无筛选）',
    logoSubtitle: 'Security Vulnerability Report',
    topCaption: 'Cyber Security Analysis Snapshot',
    version: '版本',
    exportedAt: '导出时间',
    summaryAria: '重点摘要',
    filtersSection: '筛选条件',
    summarySection: '统计摘要',
    detailsSection: '漏洞明细',
    noDetails: '（没有符合条件的漏洞）',
    generatedBy: 'Generated by Confession',
    severityTag: 'severity',
    statusTag: 'status',
    humanStatusTag: 'humanStatus',
    description: '描述',
    risk: '风险',
    fixSuggestion: '修复建议',
    na: 'N/A',
  },
  en: {
    htmlLang: 'en',
    title: 'Confession Vulnerability Export Report',
    statTotal: 'Total',
    statOpen: 'Open',
    statFixed: 'Fixed',
    statIgnored: 'Ignored',
    statDanger: 'Critical+High',
    summaryTotal: 'Total',
    summaryBySeverity: 'By Severity',
    summaryByStatus: 'By Status',
    summaryByHumanStatus: 'By Review Status',
    summaryByType: 'By Vulnerability Type',
    noFilters: '(No filters)',
    logoSubtitle: 'Security Vulnerability Report',
    topCaption: 'Cyber Security Analysis Snapshot',
    version: 'Version',
    exportedAt: 'Exported At',
    summaryAria: 'Summary',
    filtersSection: 'Filters',
    summarySection: 'Summary',
    detailsSection: 'Vulnerability Details',
    noDetails: '(No vulnerabilities match the filters)',
    generatedBy: 'Generated by Confession',
    severityTag: 'severity',
    statusTag: 'status',
    humanStatusTag: 'humanStatus',
    description: 'Description',
    risk: 'Risk',
    fixSuggestion: 'Fix Suggestion',
    na: 'N/A',
  },
}
